let cat_details = {
  "data": [{
      "grade_name": "General Purpose",
      "actual_period_str": "Dec-2021",
      "data_ts": "2021-10-04T15:12:08Z",
      "author_id": "AU10",
      "dtype": "price_direct",
      "actual_period": "2021-12-01T00:00:00Z",
      "feedstock": "Styrene",
      "feedstock_id": "Z003",
      "indirects_price_forecast": "NO",
      "billing_rate_forecast": "NO",
      "unit": "MT",
      "sources": "Polymer Update",
      "market_overview": "ABS prices marginally increased in August as supply shortage continued in August due to low imports from Asia, ACN production issues and resulting lower output and outage at INEOS, Belgium. \nHousehold appliances, electronics, furniture and toys witnessed firm demand trends. However, summer break in August provided a slight respite from the strong demand trends. European styrene prices dropped 1.2% following a drop in the upstream benzene prices and a weakened downstream demand",
      "sub_category_name": "ABS",
      "location_id": "AX,AL,AD,AT,BY,BE,BA,BG,HR,CZ,DK,EE,FO,FI,FR,DE,GI,GR,GG,VA,HU,IS,IE,IM,IT,JE,LV,LI,LT,LU,MT,MD,MC,ME,NL,MK,NO,PL,PT,RO,RU,SM,RS,SK,SI,ES,SJ,SE,CH,UA,GB,XK",
      "fc_id": "57314c1f-fa9c-3f6d-8aaf-b277e3f3b182",
      "guidance": "FOB Rotterdam, Contract Prices",
      "sub_category_data_ts": "2021-10-04T15:12:16Z",
      "sub_category_uuid": "756ac945-ea7f-11ea-acc0-0a730e7eabfe",
      "grade_data_ts": "2021-10-04T15:12:08Z",
      "grade_type_id": "GT01",
      "region": "Europe",
      "percentage_change": -8.2,
      "currency": "EUR",
      "input_cost": "NO",
      "cost_structure": "YES",
      "price_id": "D015-01_AX,AL,AD,AT,BY,BE,BA,BG,HR,CZ,DK,EE,FO,FI,FR,DE,GI,GR,GG,VA,HU,IS,IE,IM,IT,JE,LV,LI,LT,LU,MT,MD,MC,ME,NL,MK,NO,PL,PT,RO,RU,SM,RS,SK,SI,ES,SJ,SE,CH,UA,GB,XK_Dec-2021",
      "category_name": "Engineered Resins",
      "hovering_indicator": "",
      "location_data_ts": "2021-10-04T15:12:17Z",
      "price_point": 2839.95,
      "sub_category_id": "D015",
      "related_sub_category_id": "D014,D016,D107",
      "grade_id": "D015-01",
      "grade_type_name": "Grade",
      "author_name": "Posina Dayakar, Category Lead - Chemicals",
      "accuracy_3_months": 95,
      "substitute": "Polycarbonate",
      "indices": "NO",
      "related_sub_category": "Polystyrene,Nylon,Polycarbonate",
      "country": "AX,AL,AD,AT,BY,BE,BA,BG,HR,CZ,DK,EE,FO,FI,FR,DE,GI,GR,GG,VA,HU,IS,IE,IM,IT,JE,LV,LI,LT,LU,MT,MD,MC,ME,NL,MK,NO,PL,PT,RO,RU,SM,RS,SK,SI,ES,SJ,SE,CH,UA,GB,XK",
      "category_id": "31",
      "accuracy_6_months": 90,
      "price_forecast": "YES",
      "market_outlook": "ABS is likely to remain in short supply due to upcoming turnarounds and ACN production issues. Asian imports, particularly from South Korea is unlikely owing to the logistic issues and lead times from 12-16 weeks. Demand, particularly from household sector, for appliances, electronics and toys to remain elevated till Q4 2021. Shutdowns among vehicle manufacturers likely to dampen auto demand for ABS. European styrene prices are estimated to increase by 2-4% in the short term. Overall, supply shortage, strong demand and firming styrene prices to propel ABS price hikes \n: ABS prices to drop in medium term from the current levels owing to softer demand in December 2021, capacity additions in Europe and drop in styrene prices\n: Demand is expected to pick up from Q1 2022 as activities resume as buyers restock supplies ahead of peak demand in Q2 2021. ABS prices are estimated to increase in Q2 2022 with firming demand.",
      "period_frequency": "Monthly",
      "accuracy_12_months": 83,
      "substitute_id": "D107"
    },
    {
      "grade_name": "General Purpose",
      "actual_period_str": "Nov-2021",
      "data_ts": "2021-10-04T15:12:08Z",
      "author_id": "AU10",
      "dtype": "price_direct",
      "actual_period": "2021-11-01T00:00:00Z",
      "feedstock": "Styrene",
      "feedstock_id": "Z003",
      "indirects_price_forecast": "NO",
      "billing_rate_forecast": "NO",
      "unit": "MT",
      "sources": "Polymer Update",
      "market_overview": "ABS prices dropped in August following a decline in styrene prices. Styrene prices dropped by 7.4% in August 2021 due to decline in the upstream benzene prices and an ample supply situation. ABS demand picked up in August as buyers build inventory ahead of peak demand period. However, port congestion and resulting delays in cargos coupled with COVID-19 flare ups continued to impact the demand. ABS operating rates improved in the region following improved demand. With the absence of turnarounds and high freight rates that resulted in limited exports to US and Europe, ABS supply in Asia remained ample.",
      "sub_category_name": "ABS",
      "location_id": "AF,AM,AZ,BD,BT,CN,GE,HK,IN,IR,JP,KZ,KR,KP,KG,MO,MV,MN,NP,PK,LK,TW,TJ,TM,UZ",
      "fc_id": "2a49ee7c-0550-36b8-a47d-c9d599d0df1a",
      "guidance": "CFR Asia, Spot Prices",
      "sub_category_data_ts": "2021-10-04T15:12:16Z",
      "sub_category_uuid": "756ac945-ea7f-11ea-acc0-0a730e7eabfe",
      "grade_data_ts": "2021-10-04T15:12:08Z",
      "grade_type_id": "GT01",
      "region": "Asia",
      "percentage_change": 1.6,
      "currency": "USD",
      "input_cost": "NO",
      "cost_structure": "YES",
      "price_id": "D015-01_AF,AM,AZ,BD,BT,CN,GE,HK,IN,IR,JP,KZ,KR,KP,KG,MO,MV,MN,NP,PK,LK,TW,TJ,TM,UZ_Nov-2021",
      "category_name": "Engineered Resins",
      "hovering_indicator": "",
      "location_data_ts": "2021-10-04T15:12:17Z",
      "price_point": 2520.71,
      "sub_category_id": "D015",
      "related_sub_category_id": "D014,D016,D107",
      "grade_id": "D015-01",
      "grade_type_name": "Grade",
      "author_name": "Posina Dayakar, Category Lead - Chemicals",
      "accuracy_3_months": 95,
      "substitute": "Polycarbonate",
      "indices": "NO",
      "related_sub_category": "Polystyrene,Nylon,Polycarbonate",
      "country": "AF,AM,AZ,BD,BT,CN,GE,HK,IN,IR,JP,KZ,KR,KP,KG,MO,MV,MN,NP,PK,LK,TW,TJ,TM,UZ",
      "category_id": "31",
      "accuracy_6_months": 90,
      "price_forecast": "YES",
      "market_outlook": "Onset of traditional peak manufacturing activities in September-October 2021 for electronics, home appliances and construction to strengthen ABS demand. Market participants are cautious as container shortages and record high freight costs could hamper demand due to lower margins for buyers. Asian ABS market to lengthen with a capacity addition of 0.45 MMT slated to come online in September 2021. However, the regional styrene prices are estimated to follow an expected hike in the upstream benzene prices, and increase by 2-4% in the short term supporting a hike in ABS prices\n: With an increase in styrene prices and strong demand ABS prices to witness an overall uptrend during Q4 2021. However, drop in buying momentum during December 2021 to lower ABS prices \n: In long term, ABS prices are expected to pick up following Lunar New Year in February 2022 due to firming demand ahead of peak season in Q2 2022.",
      "period_frequency": "Monthly",
      "accuracy_12_months": 83,
      "substitute_id": "D107"
    },
    {
      "grade_name": "General Purpose",
      "actual_period_str": "Dec-2021",
      "data_ts": "2021-10-04T15:12:08Z",
      "author_id": "AU10",
      "dtype": "price_direct",
      "actual_period": "2021-12-01T00:00:00Z",
      "feedstock": "Styrene",
      "feedstock_id": "Z003",
      "indirects_price_forecast": "NO",
      "billing_rate_forecast": "NO",
      "unit": "MT",
      "sources": "Polymer Update",
      "market_overview": "ABS prices dropped in August following a decline in styrene prices. Styrene prices dropped by 7.4% in August 2021 due to decline in the upstream benzene prices and an ample supply situation. ABS demand picked up in August as buyers build inventory ahead of peak demand period. However, port congestion and resulting delays in cargos coupled with COVID-19 flare ups continued to impact the demand. ABS operating rates improved in the region following improved demand. With the absence of turnarounds and high freight rates that resulted in limited exports to US and Europe, ABS supply in Asia remained ample.",
      "sub_category_name": "ABS",
      "location_id": "AF,AM,AZ,BD,BT,CN,GE,HK,IN,IR,JP,KZ,KR,KP,KG,MO,MV,MN,NP,PK,LK,TW,TJ,TM,UZ",
      "fc_id": "a3a7e648-d7a6-36a0-88aa-edd84470e3b2",
      "guidance": "CFR Asia, Spot Prices",
      "sub_category_data_ts": "2021-10-04T15:12:16Z",
      "sub_category_uuid": "756ac945-ea7f-11ea-acc0-0a730e7eabfe",
      "grade_data_ts": "2021-10-04T15:12:08Z",
      "grade_type_id": "GT01",
      "region": "Asia",
      "percentage_change": -6.9,
      "currency": "USD",
      "input_cost": "NO",
      "cost_structure": "YES",
      "price_id": "D015-01_AF,AM,AZ,BD,BT,CN,GE,HK,IN,IR,JP,KZ,KR,KP,KG,MO,MV,MN,NP,PK,LK,TW,TJ,TM,UZ_Dec-2021",
      "category_name": "Engineered Resins",
      "hovering_indicator": "",
      "location_data_ts": "2021-10-04T15:12:17Z",
      "price_point": 2346.78,
      "sub_category_id": "D015",
      "related_sub_category_id": "D014,D016,D107",
      "grade_id": "D015-01",
      "grade_type_name": "Grade",
      "author_name": "Posina Dayakar, Category Lead - Chemicals",
      "accuracy_3_months": 95,
      "substitute": "Polycarbonate",
      "indices": "NO",
      "related_sub_category": "Polystyrene,Nylon,Polycarbonate",
      "country": "AF,AM,AZ,BD,BT,CN,GE,HK,IN,IR,JP,KZ,KR,KP,KG,MO,MV,MN,NP,PK,LK,TW,TJ,TM,UZ",
      "category_id": "31",
      "accuracy_6_months": 90,
      "price_forecast": "YES",
      "market_outlook": "Onset of traditional peak manufacturing activities in September-October 2021 for electronics, home appliances and construction to strengthen ABS demand. Market participants are cautious as container shortages and record high freight costs could hamper demand due to lower margins for buyers. Asian ABS market to lengthen with a capacity addition of 0.45 MMT slated to come online in September 2021. However, the regional styrene prices are estimated to follow an expected hike in the upstream benzene prices, and increase by 2-4% in the short term supporting a hike in ABS prices\n: With an increase in styrene prices and strong demand ABS prices to witness an overall uptrend during Q4 2021. However, drop in buying momentum during December 2021 to lower ABS prices \n: In long term, ABS prices are expected to pick up following Lunar New Year in February 2022 due to firming demand ahead of peak season in Q2 2022.",
      "period_frequency": "Monthly",
      "accuracy_12_months": 83,
      "substitute_id": "D107"
    },
    {
      "grade_name": "General Purpose",
      "actual_period_str": "Nov-2021",
      "data_ts": "2021-10-04T15:12:08Z",
      "author_id": "AU10",
      "dtype": "price_direct",
      "actual_period": "2021-11-01T00:00:00Z",
      "feedstock": "Styrene",
      "feedstock_id": "Z003",
      "indirects_price_forecast": "NO",
      "billing_rate_forecast": "NO",
      "unit": "MT",
      "sources": "Polymer Update",
      "market_overview": "Rising styrene prices and tight supply increase US ABS prices in August. Faced with limited import availability, logistics constraints, long lead times and curtailed domestic outputs from key suppliers, ABS supply continued to remain tight in US. Strong demand was seen for electronics, appliances and toys. With production cuts from auto manufacturers, auto demand remained relatively softer. US styrene prices increased by 1.6% due to a healthy downstream demand from the packaging and household durables sectors. Nearly 38% of the regional styrene production went offline towards the end of August 2021 as hurricane Ida made landfall in the US.",
      "sub_category_name": "ABS",
      "location_id": "BM,CA,GL,PM,US",
      "fc_id": "5f85c6b8-684f-3f7f-ba4f-a5c60531dde6",
      "guidance": "Delivered Railcar, Contract Prices",
      "sub_category_data_ts": "2021-10-04T15:12:16Z",
      "sub_category_uuid": "756ac945-ea7f-11ea-acc0-0a730e7eabfe",
      "grade_data_ts": "2021-10-04T15:12:08Z",
      "grade_type_id": "GT01",
      "region": "North America",
      "percentage_change": 0.8,
      "currency": "USD",
      "input_cost": "NO",
      "cost_structure": "YES",
      "price_id": "D015-01_BM,CA,GL,PM,US_Nov-2021",
      "category_name": "Engineered Resins",
      "hovering_indicator": "",
      "location_data_ts": "2021-10-04T15:12:19Z",
      "price_point": 3021.9,
      "sub_category_id": "D015",
      "related_sub_category_id": "D014,D016,D107",
      "grade_id": "D015-01",
      "grade_type_name": "Grade",
      "author_name": "Posina Dayakar, Category Lead - Chemicals",
      "accuracy_3_months": 95,
      "substitute": "Polycarbonate",
      "indices": "NO",
      "related_sub_category": "Polystyrene,Nylon,Polycarbonate",
      "country": "BM,CA,GL,PM,US",
      "category_id": "31",
      "accuracy_6_months": 90,
      "price_forecast": "YES",
      "market_outlook": "ABS supply tightness to continue in short term with limited availability of imports and curtailed outputs due to turnarounds and force majeures from key suppliers. Demand for ABS from construction , appliances and toys are likely to remain robust in short term. However auto demand to continue to remain soft in the near term. Styrene prices to increase by 6-8% in the short term due to a tightness in regional styrene supply is expected during the short term till key suppliers CosMar and AmSty restart their plants for styrene production. Higher styrene prices and tight supply to push for ABS price hikes in short term \n: Cold weather and weaker buying momentum to lower ABS prices in December 2021. ABS prices are expected to witness an overall downtrend in Q1 2022\n: Onset of restocking activities in Q2 2022 to strengthen ABS prices from Q2 2022. The recovery of auto demand is expected in 2022 as microchip shortage gets alleviated, which could strengthen ABS demand in long term.",
      "period_frequency": "Monthly",
      "accuracy_12_months": 83,
      "substitute_id": "D107"
    },
    {
      "grade_name": "General Purpose",
      "actual_period_str": "Nov-2021",
      "data_ts": "2021-10-04T15:12:08Z",
      "author_id": "AU10",
      "dtype": "price_direct",
      "actual_period": "2021-11-01T00:00:00Z",
      "feedstock": "Styrene",
      "feedstock_id": "Z003",
      "indirects_price_forecast": "NO",
      "billing_rate_forecast": "NO",
      "unit": "MT",
      "sources": "Polymer Update",
      "market_overview": "ABS prices marginally increased in August as supply shortage continued in August due to low imports from Asia, ACN production issues and resulting lower output and outage at INEOS, Belgium. \nHousehold appliances, electronics, furniture and toys witnessed firm demand trends. However, summer break in August provided a slight respite from the strong demand trends. European styrene prices dropped 1.2% following a drop in the upstream benzene prices and a weakened downstream demand",
      "sub_category_name": "ABS",
      "location_id": "AX,AL,AD,AT,BY,BE,BA,BG,HR,CZ,DK,EE,FO,FI,FR,DE,GI,GR,GG,VA,HU,IS,IE,IM,IT,JE,LV,LI,LT,LU,MT,MD,MC,ME,NL,MK,NO,PL,PT,RO,RU,SM,RS,SK,SI,ES,SJ,SE,CH,UA,GB,XK",
      "fc_id": "06372e5e-d292-3758-a3db-01760b5334cd",
      "guidance": "FOB Rotterdam, Contract Prices",
      "sub_category_data_ts": "2021-10-04T15:12:16Z",
      "sub_category_uuid": "756ac945-ea7f-11ea-acc0-0a730e7eabfe",
      "grade_data_ts": "2021-10-04T15:12:08Z",
      "grade_type_id": "GT01",
      "region": "Europe",
      "percentage_change": 2,
      "currency": "EUR",
      "input_cost": "NO",
      "cost_structure": "YES",
      "price_id": "D015-01_AX,AL,AD,AT,BY,BE,BA,BG,HR,CZ,DK,EE,FO,FI,FR,DE,GI,GR,GG,VA,HU,IS,IE,IM,IT,JE,LV,LI,LT,LU,MT,MD,MC,ME,NL,MK,NO,PL,PT,RO,RU,SM,RS,SK,SI,ES,SJ,SE,CH,UA,GB,XK_Nov-2021",
      "category_name": "Engineered Resins",
      "hovering_indicator": "",
      "location_data_ts": "2021-10-04T15:12:17Z",
      "price_point": 3093.63,
      "sub_category_id": "D015",
      "related_sub_category_id": "D014,D016,D107",
      "grade_id": "D015-01",
      "grade_type_name": "Grade",
      "author_name": "Posina Dayakar, Category Lead - Chemicals",
      "accuracy_3_months": 95,
      "substitute": "Polycarbonate",
      "indices": "NO",
      "related_sub_category": "Polystyrene,Nylon,Polycarbonate",
      "country": "AX,AL,AD,AT,BY,BE,BA,BG,HR,CZ,DK,EE,FO,FI,FR,DE,GI,GR,GG,VA,HU,IS,IE,IM,IT,JE,LV,LI,LT,LU,MT,MD,MC,ME,NL,MK,NO,PL,PT,RO,RU,SM,RS,SK,SI,ES,SJ,SE,CH,UA,GB,XK",
      "category_id": "31",
      "accuracy_6_months": 90,
      "price_forecast": "YES",
      "market_outlook": "ABS is likely to remain in short supply due to upcoming turnarounds and ACN production issues. Asian imports, particularly from South Korea is unlikely owing to the logistic issues and lead times from 12-16 weeks. Demand, particularly from household sector, for appliances, electronics and toys to remain elevated till Q4 2021. Shutdowns among vehicle manufacturers likely to dampen auto demand for ABS. European styrene prices are estimated to increase by 2-4% in the short term. Overall, supply shortage, strong demand and firming styrene prices to propel ABS price hikes \n: ABS prices to drop in medium term from the current levels owing to softer demand in December 2021, capacity additions in Europe and drop in styrene prices\n: Demand is expected to pick up from Q1 2022 as activities resume as buyers restock supplies ahead of peak demand in Q2 2021. ABS prices are estimated to increase in Q2 2022 with firming demand.",
      "period_frequency": "Monthly",
      "accuracy_12_months": 83,
      "substitute_id": "D107"
    },
    {
      "grade_name": "General Purpose",
      "actual_period_str": "Dec-2021",
      "data_ts": "2021-10-04T15:12:08Z",
      "author_id": "AU10",
      "dtype": "price_direct",
      "actual_period": "2021-12-01T00:00:00Z",
      "feedstock": "Styrene",
      "feedstock_id": "Z003",
      "indirects_price_forecast": "NO",
      "billing_rate_forecast": "NO",
      "unit": "MT",
      "sources": "Polymer Update",
      "market_overview": "Rising styrene prices and tight supply increase US ABS prices in August. Faced with limited import availability, logistics constraints, long lead times and curtailed domestic outputs from key suppliers, ABS supply continued to remain tight in US. Strong demand was seen for electronics, appliances and toys. With production cuts from auto manufacturers, auto demand remained relatively softer. US styrene prices increased by 1.6% due to a healthy downstream demand from the packaging and household durables sectors. Nearly 38% of the regional styrene production went offline towards the end of August 2021 as hurricane Ida made landfall in the US.",
      "sub_category_name": "ABS",
      "location_id": "BM,CA,GL,PM,US",
      "fc_id": "f3fca249-65f7-3a08-a0e5-8c7b3367e13e",
      "guidance": "Delivered Railcar, Contract Prices",
      "sub_category_data_ts": "2021-10-04T15:12:16Z",
      "sub_category_uuid": "756ac945-ea7f-11ea-acc0-0a730e7eabfe",
      "grade_data_ts": "2021-10-04T15:12:08Z",
      "grade_type_id": "GT01",
      "region": "North America",
      "percentage_change": -7.2,
      "currency": "USD",
      "input_cost": "NO",
      "cost_structure": "YES",
      "price_id": "D015-01_BM,CA,GL,PM,US_Dec-2021",
      "category_name": "Engineered Resins",
      "hovering_indicator": "",
      "location_data_ts": "2021-10-04T15:12:19Z",
      "price_point": 2804.32,
      "sub_category_id": "D015",
      "related_sub_category_id": "D014,D016,D107",
      "grade_id": "D015-01",
      "grade_type_name": "Grade",
      "author_name": "Posina Dayakar, Category Lead - Chemicals",
      "accuracy_3_months": 95,
      "substitute": "Polycarbonate",
      "indices": "NO",
      "related_sub_category": "Polystyrene,Nylon,Polycarbonate",
      "country": "BM,CA,GL,PM,US",
      "category_id": "31",
      "accuracy_6_months": 90,
      "price_forecast": "YES",
      "market_outlook": "ABS supply tightness to continue in short term with limited availability of imports and curtailed outputs due to turnarounds and force majeures from key suppliers. Demand for ABS from construction , appliances and toys are likely to remain robust in short term. However auto demand to continue to remain soft in the near term. Styrene prices to increase by 6-8% in the short term due to a tightness in regional styrene supply is expected during the short term till key suppliers CosMar and AmSty restart their plants for styrene production. Higher styrene prices and tight supply to push for ABS price hikes in short term \n: Cold weather and weaker buying momentum to lower ABS prices in December 2021. ABS prices are expected to witness an overall downtrend in Q1 2022\n: Onset of restocking activities in Q2 2022 to strengthen ABS prices from Q2 2022. The recovery of auto demand is expected in 2022 as microchip shortage gets alleviated, which could strengthen ABS demand in long term.",
      "period_frequency": "Monthly",
      "accuracy_12_months": 83,
      "substitute_id": "D107"
    }
  ]
}

console.log(cat_details)